#! /usr/bin/env python


class BrownClusters:
    """
    This class manages brown cluster as generated by P. Liang's
    clustering package. By hypothesis the set of wordforms is
    partitioned by the clusters : no wordform can belong to more than
    one cluster.
    """
    
    def __init__(self):
        self.word2cls_dic = {}
        self.

    def get_cls(self,wordform,defaultval='UNK'):
        """
        Returns the cluster to which this word belongs or a default
        value if this word is unknown to the clustering
        """
        pass

    def word_emission_prob(self,wordform,logprob=True):
        """
        @return P(w|C) that is the probability that this word is
        generated by its cluster C (which is automatically retrieved)
        """
        

    
    @staticmethod
    def readfile(infilename):
        istream = open(infilename)
        for line in istream:
            do sth
        istream.close()
